Contributing guidelines
deta/deta-python pull request #15
Opened 2021-04-15 14:53 UTC by yankeexe

## Changes

- Added Contributing Guidelines for the project. 
- Update SDK packaging:
  -  to separate out dev and required dependencies.
  - Proper README for [SDK PyPI page](https://pypi.org/project/deta/) with `long_description`
- pre-commit hooks for code formatting
- Black formatter configuration using `pyproject.toml`

2021-04-16 15:28 UTC, yankeexe commented
> What does this do. When does it run?

@abdelhai  I believe you are asking about the `pre-commit hooks`. It runs right after we `git commit` to check if the changes made are well formatted, documented, follows best practices and such.

2021-05-20 17:46 UTC, abdelhai commented
@yankeexe could you resolve the merge conflicts? cheers!

2021-05-20 18:36 UTC, yankeexe commented
> @yankeexe could you resolve the merge conflicts? cheers!

@abdelhai Resolved, can you review it? 🙂

2021-05-20 20:10 UTC, abdelhai requested changes

2021-05-20 20:10 UTC, abdelhai commented on Makefile
> +	@python3 -m twine upload dist/*
It's fine to use `python` since it will use the one inside the venv, which should be v3.

2021-05-20 20:10 UTC, abdelhai commented on CONTRIBUTING.md
> +source venv/bin/activate
```suggestion
python3 -m venv .venv

# activate virtualenv
source .venv/bin/activate
```

we like the `.venv` convention :)

2021-05-20 20:10 UTC, abdelhai commented on setup.py
> +requirements = ["python-dotenv"]
Should this be here? It's a dev/test dependency that could be in a `requirements.dev.txt` or similar.

2021-05-20 20:10 UTC, abdelhai commented on pyproject.toml
> +target-version = ['py36', 'py37', 'py38']
what about 3.9?
```suggestion
target-version = ['py36', 'py37', 'py38', 'py39']
```

2021-05-20 20:10 UTC, abdelhai commented on pyproject.toml
> +[tool.black]
What's the benefit of having a `pyproject.toml`? Looks like it's not adding anything important. Rather adding more files and config and therefor more things that need maintenance.

2022-05-16 20:05 UTC, closed without merging